//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergyRoom.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnergyRoom.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPasswordText {
            get {
                return ResourceManager.GetString("ConfirmPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an account to start doing more.
        /// </summary>
        public static string CreateAccountText {
            get {
                return ResourceManager.GetString("CreateAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with Facebook.
        /// </summary>
        public static string FBLogin {
            get {
                return ResourceManager.GetString("FBLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG IN.
        /// </summary>
        public static string LOG_IN {
            get {
                return ResourceManager.GetString("LOG IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s get to work.
        /// </summary>
        public static string LogInDescr {
            get {
                return ResourceManager.GetString("LogInDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string LoginQuestion {
            get {
                return ResourceManager.GetString("LoginQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LogInText {
            get {
                return ResourceManager.GetString("LogInText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UsernameText
        {
            get
            {
                return ResourceManager.GetString("UsernameText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameText {
            get {
                return ResourceManager.GetString("NameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordText {
            get {
                return ResourceManager.GetString("PasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTER.
        /// </summary>
        public static string REGISTER {
            get {
                return ResourceManager.GetString("REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        public static string SignUpQuestion {
            get {
                return ResourceManager.GetString("SignUpQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string SignUpText {
            get {
                return ResourceManager.GetString("SignUpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or create an account using social media.
        /// </summary>
        public static string SocialDescr {
            get {
                return ResourceManager.GetString("SocialDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string WeekText {
            get {
                return ResourceManager.GetString("WeekText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ForgotPassword.
        /// </summary>
        public static string ForgotPasswordText
        {
            get
            {
                return ResourceManager.GetString("ForgotPasswordText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        public static string LOGIN
        {
            get
            {
                return ResourceManager.GetString("LOGIN", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FBLoginText.
        /// </summary>
        public static string FBLoginText
        {
            get
            {
                return ResourceManager.GetString("FBLoginText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UserCanTakePlaceInEventText.
        /// </summary>
        public static string UserCanTakePlaceInEventText
        {
            get
            {
                return ResourceManager.GetString("UserCanTakePlaceInEventText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UserHasBookedEventText.
        /// </summary>
        public static string UserHasBookedEventText
        {
            get
            {
                return ResourceManager.GetString("UserHasBookedEventText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UsersThatHaveBookedText.
        /// </summary>
        public static string UsersThatHaveBookedText
        {
            get
            {
                return ResourceManager.GetString("UsersThatHaveBookedText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BookText.
        /// </summary>
        public static string BookText
        {
            get
            {
                return ResourceManager.GetString("BookText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to WithdrawText.
        /// </summary>
        public static string WithdrawText
        {
            get
            {
                return ResourceManager.GetString("WithdrawText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NoBookingsOnEventText.
        /// </summary>
        public static string NoBookingsOnEventText
        {
            get
            {
                return ResourceManager.GetString("NoBookingsOnEventText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EventInfo.
        /// </summary>
        public static string EventInfoText
        {
            get
            {
                return ResourceManager.GetString("EventInfoText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DeleteText.
        /// </summary>
        public static string DeleteText
        {
            get
            {
                return ResourceManager.GetString("DeleteText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CancelText.
        /// </summary>
        public static string CancelText
        {
            get
            {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ScheduleText.
        /// </summary>
        public static string ScheduleText
        {
            get
            {
                return ResourceManager.GetString("ScheduleText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AccountText.
        /// </summary>
        public static string AccountText
        {
            get
            {
                return ResourceManager.GetString("AccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneText.
        /// </summary>
        public static string PhoneText
        {
            get
            {
                return ResourceManager.GetString("PhoneText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ValidEmailText.
        /// </summary>
        public static string ValidEmailText
        {
            get
            {
                return ResourceManager.GetString("ValidEmailText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DateText.
        /// </summary>
        public static string DateText
        {
            get
            {
                return ResourceManager.GetString("DateText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TimeText.
        /// </summary>
        public static string TimeText
        {
            get
            {
                return ResourceManager.GetString("TimeText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SelectPictureText.
        /// </summary>
        public static string SelectPictureText
        {
            get
            {
                return ResourceManager.GetString("SelectPictureText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NewPictureText.
        /// </summary>
        public static string NewPictureText
        {
            get
            {
                return ResourceManager.GetString("NewPictureText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UploadText.
        /// </summary>
        public static string UploadText
        {
            get
            {
                return ResourceManager.GetString("UploadText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LogOutText.
        /// </summary>
        public static string LogOutText
        {
            get
            {
                return ResourceManager.GetString("LogOutText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UploadedText.
        /// </summary>
        public static string UploadedText
        {
            get
            {
                return ResourceManager.GetString("UploadedText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UploadSuccessfulText.
        /// </summary>
        public static string UploadSuccessfulText
        {
            get
            {
                return ResourceManager.GetString("UploadSuccessfulText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EventsList.
        /// </summary>
        public static string EventsList
        {
            get
            {
                return ResourceManager.GetString("EventsList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EmailInUseTitle.
        /// </summary>
        public static string EmailInUseTitle
        {
            get
            {
                return ResourceManager.GetString("EmailInUseTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UsernameInUseTitle.
        /// </summary>
        public static string UsernameInUseTitle
        {
            get
            {
                return ResourceManager.GetString("UsernameInUseTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EmailInUseDescr.
        /// </summary>
        public static string EmailInUseDescr
        {
            get
            {
                return ResourceManager.GetString("EmailInUseDescr", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UsernameInUseDescr.
        /// </summary>
        public static string UsernameInUseDescr
        {
            get
            {
                return ResourceManager.GetString("UsernameInUseDescr", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PasswordsDoNotMatchTitle.
        /// </summary>
        public static string PasswordsDoNotMatchTitle
        {
            get
            {
                return ResourceManager.GetString("PasswordsDoNotMatchTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PasswordsDoNotMatchDescr.
        /// </summary>
        public static string PasswordsDoNotMatchDescr
        {
            get
            {
                return ResourceManager.GetString("PasswordsDoNotMatchDescr", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TrainerIsText.
        /// </summary>
        public static string TrainerIsText
        {
            get
            {
                return ResourceManager.GetString("TrainerIsText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UserNotFoundTitle.
        /// </summary>
        public static string UserNotFoundTitle
        {
            get
            {
                return ResourceManager.GetString("UserNotFoundTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UserNotFoundDescr.
        /// </summary>
        public static string UserNotFoundDescr
        {
            get
            {
                return ResourceManager.GetString("UserNotFoundDescr", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AddNewEventText.
        /// </summary>
        public static string AddNewEventText
        {
            get
            {
                return ResourceManager.GetString("AddNewEventText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AddText.
        /// </summary>
        public static string AddText
        {
            get
            {
                return ResourceManager.GetString("AddText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TypeText.
        /// </summary>
        public static string TypeText
        {
            get
            {
                return ResourceManager.GetString("TypeText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to StartTimeText.
        /// </summary>
        public static string StartTimeText
        {
            get
            {
                return ResourceManager.GetString("StartTimeText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EndTimeText.
        /// </summary>
        public static string EndTimeText
        {
            get
            {
                return ResourceManager.GetString("EndTimeText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ProfileText.
        /// </summary>
        public static string ProfileText
        {
            get
            {
                return ResourceManager.GetString("ProfileText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ChangePhotoTitleText.
        /// </summary>
        public static string ChangePhotoTitleText
        {
            get
            {
                return ResourceManager.GetString("ChangePhotoTitleText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ChangePhotoDescrText.
        /// </summary>
        public static string ChangePhotoDescrText
        {
            get
            {
                return ResourceManager.GetString("ChangePhotoDescrText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CameraText.
        /// </summary>
        public static string CameraText
        {
            get
            {
                return ResourceManager.GetString("CameraText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CollectionText.
        /// </summary>
        public static string CollectionText
        {
            get
            {
                return ResourceManager.GetString("CollectionText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ChangePhoneText.
        /// </summary>
        public static string ChangePhoneText
        {
            get
            {
                return ResourceManager.GetString("ChangePhoneText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ChangeEmailText.
        /// </summary>
        public static string ChangeEmailText
        {
            get
            {
                return ResourceManager.GetString("ChangeEmailText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ChangeText.
        /// </summary>
        public static string ChangeText
        {
            get
            {
                return ResourceManager.GetString("ChangeText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NotificeText.
        /// </summary>
        public static string NotificeText
        {
            get
            {
                return ResourceManager.GetString("NotificeText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PhoneChangeSuccessfulText.
        /// </summary>
        public static string PhoneChangeSuccessfulText
        {
            get
            {
                return ResourceManager.GetString("PhoneChangeSuccessfulText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ChangeEmailRequestSentTitle.
        /// </summary>
        public static string ChangeEmailRequestSentTitle
        {
            get
            {
                return ResourceManager.GetString("ChangeEmailRequestSentTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ChangeEmailRequestSentDescr.
        /// </summary>
        public static string ChangeEmailRequestSentDescr
        {
            get
            {
                return ResourceManager.GetString("ChangeEmailRequestSentDescr", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ChangeEmailAcceptedTitle.
        /// </summary>
        public static string ChangeEmailAcceptedTitle
        {
            get
            {
                return ResourceManager.GetString("ChangeEmailAcceptedTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ChangeEmailAcceptedDescr.
        /// </summary>
        public static string ChangeEmailAcceptedDescr
        {
            get
            {
                return ResourceManager.GetString("ChangeEmailAcceptedDescr", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DisconnectedText.
        /// </summary>
        public static string DisconnectedText
        {
            get
            {
                return ResourceManager.GetString("DisconnectedText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EditText.
        /// </summary>
        public static string EditText
        {
            get
            {
                return ResourceManager.GetString("EditText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SubmitText.
        /// </summary>
        public static string SubmitText
        {
            get
            {
                return ResourceManager.GetString("SubmitText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ForgotPasswordDescr.
        /// </summary>
        public static string ForgotPasswordDescr
        {
            get
            {
                return ResourceManager.GetString("ForgotPasswordDescr", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ForgotPasswordRun.
        /// </summary>
        public static string ForgotPasswordRun
        {
            get
            {
                return ResourceManager.GetString("ForgotPasswordRun", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RecordVoicePrivacy.
        /// </summary>
        public static string RecordVoicePrivacy
        {
            get
            {
                return ResourceManager.GetString("RecordVoicePrivacy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VersionText.
        /// </summary>
        public static string VersionText
        {
            get
            {
                return ResourceManager.GetString("VersionText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GymnastText.
        /// </summary>
        public static string GymnastText
        {
            get
            {
                return ResourceManager.GetString("GymnastText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AtText.
        /// </summary>
        public static string AtText
        {
            get
            {
                return ResourceManager.GetString("AtText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NewEventText.
        /// </summary>
        public static string NewEventText
        {
            get
            {
                return ResourceManager.GetString("NewEventText", resourceCulture);
            }
        }

    }
}
